name: Node.js Task Manager CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        env:
          MONGODB_URL: mongodb://127.0.0.1:27017/task-manager-api
        run: npm test

      - name: Generate Test Coverage
        env:
          MONGODB_URL: mongodb://127.0.0.1:27017/task-manager-api
        run: npm run test:coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

 service:
    name: Container Service Test
    needs: test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nodejs-task-manager .

      - name: Run Docker container
        run: |
          docker run -d \
            --name task-manager-api \
            -p 3000:3000 \
            -e MONGODB_URL=mongodb://host.docker.internal:27017/task-manager-api \
            nodejs-task-manager

      - name: Wait for application
        run: sleep 10

      - name: Test Health Endpoint
        run: curl --fail http://localhost:3000/health
